# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: 'Zian "Zane" Liu'
description: "Synthetic biologist, bioengineer, biosafety advocate, STEM outreach organizer, political junkie, menswear enthusiast, fountain pen user, coffee addict, and more."

# Author's info
author: 'Zian Liu'
# edit 'categories' in the front matter of every post to match this username
nickname: zian
bio: 'One upon a time, I was BioEHS President and had a minor in public policy...'
location: 'Berkeley, CA'
image: 'assets/images/zian.png'

=======
# url: 'mailto:chairmanzian@gmail.com'
image: 'assets/images/zian.png'

# short_url: 'chairmanzian@gmail.com'
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
permalink: /author/:username
permalink: /tag/:tag

# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Where things are
source:       .
destination:  ./_site
#plugins_dir:  _plugins
#layouts_dir:  _layouts
#data_dir:     _data
#includes_dir: _includes
collections:
  posts:
    output:   true


exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
