# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: 'Zian "Zane" Liu'
description: "Synthetic biologist, bioengineer, biosafety advocate, STEM outreach organizer, political junkie, menswear enthusiast, fountain pen user, coffee addict, and more."

# Author's info
author: 'Zian Liu'
# edit 'categories' in the front matter of every post to match this username
nickname: zian
bio: 'One upon a time, I was BioEHS President and had a minor in public policy...'
location: 'Berkeley, CA'
url: 'mailto:chairmanzian@gmail.com'
image: 'assets/images/zian.png'

short_url: 'chairmanzian@gmail.com'
google_analytics: 
disqus: 
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
#safe: false
#lsi: false
#username: zianliu
#repo: zianliu.giohub.io
#branch: master
#relative_source: https://zianliu.github.io/
#destination: https://zianliu.github.io/
#production_url:  https://zianliu.github.io/
#source_url:      https://github.com/zianliu/zianliu.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
